### ISSUE TITLE
`avgtime` v1.0 01/02/2023 test 

### ISSUE THREAD

**Issue by condor71** [illumine/raw-cloner#24]
Scenario :  Test speed of Samsung SSD 750 EVO 500GB  internal disk .
read buffer 1MB skip buffer 5MB

Hard Disk Specs
Model:                  Samsung SSD 750 EVO 500GB
Serial Number:      S36SNWAH743243A
LU WWN Device   Id: 5 002538 d702c0a52
User Capacity:    **500.107.862.016** bytes [500 GB]
Sector Size:           512 bytes logical/physical
Rotation Rate:       Solid State Device
Form Factor:          2.5 inches
ATA Version is:   ACS-2, ATA8-ACS T13/1699-D revision 4c
SATA Version is:  SATA 3.1, 6.0 Gb/s (current: 6.0 Gb/s)

*Parameters* 
```
input_disk = /dev/sdb 500107862016 
read_buffer = 1048576  
skip_bytes =  5242880  
```
Command
```
 sudo time ./avgtime /dev/sdb 1048576 5242880 
 
./avgtime v1.0 01/02/2023

Calculate average read time from /dev/sdb 
Using read buffer of 1048576 bytes and skip/segment bytes 5242880.
Source File/Disk size is: **500107862016** bytes.
---------------------------------------------------1048576 5242880 -> *correct*
Sample size - reads is 79490
Completed. 500107862016 
Average per read time is 3403.773468 microseconds for a sample of 79490 reads
0.28user
 85.37system 
4:32.37elapsed 
31%CPU 
(0avgtext+0avgdata 2488maxresident)k
162796800inputs+0outputs (0major+323minor)pagefaults 0swaps
```
**TEST 
PASSED**

**Comment by illumine** [comment]
good job
